"""
Export utilities: OBJ, VTK, JSON, CSV.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Any
import numpy as np


def write_obj(
    obj_path: Path,
    vertices: np.ndarray,
    faces: List[List[int]],
) -> None:
    """Write mesh to OBJ file."""
    with open(obj_path, "w") as f:
        f.write("# OBJ file generated by funifloor\n")

        for x, y, z in vertices:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")

        for face in faces:
            # OBJ is 1-indexed
            indices = " ".join(str(v + 1) for v in face)
            f.write(f"f {indices}\n")

    print(f"[EXPORT] Wrote OBJ: {obj_path}")


def write_vtk(
    vtk_path: Path,
    vertices: np.ndarray,
    faces: List[List[int]],
    cell_data: Dict[str, np.ndarray] | None = None,
    point_data: Dict[str, np.ndarray] | None = None,
) -> None:
    """
    Write mesh with data to VTK file using meshio.
    """
    try:
        import meshio
    except ImportError:
        print("[EXPORT] meshio not available, skipping VTK export")
        return

    # Convert faces to meshio cell format
    quads = [f for f in faces if len(f) == 4]
    tris = [f for f in faces if len(f) == 3]

    cells = []
    if quads:
        cells.append(("quad", np.array(quads)))
    if tris:
        cells.append(("triangle", np.array(tris)))

    mesh = meshio.Mesh(
        points=vertices,
        cells=cells,
        cell_data=cell_data or {},
        point_data=point_data or {},
    )

    mesh.write(vtk_path)
    print(f"[EXPORT] Wrote VTK: {vtk_path}")


def write_json_topology(
    json_path: Path,
    vertices: np.ndarray,
    faces: List[List[int]],
    edges: np.ndarray,
    supports: List[int],
    edge_forces: Dict[tuple, float],
) -> None:
    """Write topology and forces to JSON."""
    data = {
        "vertices": vertices.tolist(),
        "faces": faces,
        "edges": edges.tolist(),
        "supports": supports,
        "edge_forces": {f"{u},{v}": f for (u, v), f in edge_forces.items()},
    }

    with open(json_path, "w") as f:
        json.dump(data, f, indent=2)

    print(f"[EXPORT] Wrote JSON topology: {json_path}")


def write_panels_json(
    json_path: Path,
    panels: List[Any],
) -> None:
    """Write panel definitions to JSON."""
    data = {
        "n_panels": len(panels),
        "panels": [p.to_dict() for p in panels],
    }

    with open(json_path, "w") as f:
        json.dump(data, f, indent=2)

    print(f"[EXPORT] Wrote panels JSON: {json_path}")


def write_results_csv(
    csv_path: Path,
    n_elements: int,
    results: Dict[str, np.ndarray],
) -> None:
    """Write per-element results to CSV."""
    with open(csv_path, "w") as f:
        # Header
        keys = list(results.keys())
        f.write("element_id," + ",".join(keys) + "\n")

        # Data rows
        for i in range(n_elements):
            row = [str(i + 1)]  # 1-indexed element ID
            for key in keys:
                arr = results[key]
                if isinstance(arr, np.ndarray) and len(arr) > i:
                    row.append(f"{arr[i]:.6g}")
                else:
                    row.append("0")
            f.write(",".join(row) + "\n")

    print(f"[EXPORT] Wrote CSV results: {csv_path}")


def write_summary(
    txt_path: Path,
    summary: Dict[str, Any],
) -> None:
    """Write run summary to text file."""
    with open(txt_path, "w") as f:
        f.write("=" * 60 + "\n")
        f.write("FUNIFLOOR RUN SUMMARY\n")
        f.write("=" * 60 + "\n\n")

        for key, value in summary.items():
            if isinstance(value, dict):
                f.write(f"{key}:\n")
                for k2, v2 in value.items():
                    f.write(f"  {k2}: {v2}\n")
            else:
                f.write(f"{key}: {value}\n")

    print(f"[EXPORT] Wrote summary: {txt_path}")
