"""
Export mesh and results to CalculiX .inp format.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Any
import numpy as np


def write_inp(
    inp_path: Path,
    vertices: np.ndarray,
    faces: List[List[int]],
    supports: List[int],
    thickness: float,
    E: float,
    nu: float,
    pressure: float,
    job_name: str = "funifloor",
) -> None:
    """
    Write CalculiX input file for shell analysis.
    
    Args:
        inp_path: Output .inp file path
        vertices: (N, 3) vertex coordinates
        faces: List of face vertex indices (quads or tris)
        supports: List of vertex indices that are fixed
        thickness: Shell thickness
        E: Young's modulus (MPa)
        nu: Poisson's ratio
        pressure: Uniform pressure load (positive = downward, MPa or consistent units)
        job_name: CalculiX job name
    """
    with open(inp_path, "w") as f:
        f.write(f"** CalculiX input file generated by funifloor\n")
        f.write(f"** Job: {job_name}\n\n")

        # Heading
        f.write("*HEADING\n")
        f.write(f"Funicular floor shell analysis\n\n")

        # Nodes (1-indexed for CalculiX)
        f.write("*NODE, NSET=NALL\n")
        for i, (x, y, z) in enumerate(vertices):
            f.write(f"{i+1}, {x:.8f}, {y:.8f}, {z:.8f}\n")
        f.write("\n")

        # Elements
        # Determine element type based on face size
        has_quads = any(len(face) == 4 for face in faces)
        has_tris = any(len(face) == 3 for face in faces)

        elem_id = 1

        if has_quads:
            f.write("*ELEMENT, TYPE=S4, ELSET=EQUADS\n")
            for face in faces:
                if len(face) == 4:
                    # CalculiX is 1-indexed
                    nodes = ", ".join(str(v + 1) for v in face)
                    f.write(f"{elem_id}, {nodes}\n")
                    elem_id += 1
            f.write("\n")

        if has_tris:
            f.write("*ELEMENT, TYPE=S3, ELSET=ETRIS\n")
            for face in faces:
                if len(face) == 3:
                    nodes = ", ".join(str(v + 1) for v in face)
                    f.write(f"{elem_id}, {nodes}\n")
                    elem_id += 1
            f.write("\n")

        # Element set for all shells
        f.write("*ELSET, ELSET=EALL\n")
        if has_quads:
            f.write("EQUADS,\n")
        if has_tris:
            f.write("ETRIS,\n")
        f.write("\n")

        # Shell section
        f.write("*SHELL SECTION, ELSET=EALL, MATERIAL=CONCRETE\n")
        f.write(f"{thickness:.6f}\n\n")

        # Material
        f.write("*MATERIAL, NAME=CONCRETE\n")
        f.write("*ELASTIC\n")
        f.write(f"{E:.1f}, {nu:.4f}\n\n")

        # Support boundary conditions (fixed: all DOFs)
        f.write("*NSET, NSET=NSUPPORTS\n")
        for i, s in enumerate(supports):
            if (i + 1) % 10 == 0:
                f.write(f"{s + 1},\n")
            else:
                f.write(f"{s + 1}, ")
        f.write("\n\n")

        f.write("*BOUNDARY\n")
        f.write("NSUPPORTS, 1, 6, 0.0\n\n")

        # Load step
        f.write("*STEP\n")
        f.write("*STATIC\n\n")

        # Pressure load (applied to shell element faces)
        f.write("*DLOAD\n")
        f.write(f"EALL, P, {pressure:.6f}\n\n")

        # Output requests
        f.write("*NODE FILE\n")
        f.write("U\n\n")

        f.write("*EL FILE\n")
        f.write("S, E\n\n")

        # Element output for section forces (bending moments)
        f.write("*NODE PRINT, NSET=NALL\n")
        f.write("U\n\n")

        f.write("*EL PRINT, ELSET=EALL\n")
        f.write("S\n\n")

        # Section forces output (contains moments)
        f.write("*SECTION PRINT, ELSET=EALL\n")
        f.write("SOF\n\n")

        f.write("*END STEP\n")

    print(f"[FE] Wrote CalculiX input: {inp_path}")


def estimate_pressure(load_per_area: float) -> float:
    """
    Convert load per area (kN/m²) to CalculiX pressure (MPa or N/mm²).
    
    If using m/N units: kN/m² = 1e-3 N/mm² = 1e-3 MPa
    If using m/kN units: use directly
    
    We assume m/kN consistent units here.
    """
    # load_per_area in kN/m² stays as kN/m² for consistent units
    return load_per_area
